spring:
  application:
    name: member-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  packages-to-scan: io.chagchagchag.example.gateway_filter_example.member
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  version: v1
  api-docs:
    path: /api-docs
    enabled: true # for dev
  swagger-ui:
    enabled: true # for dev
    path: /swagger-ui.html
    try-it-out-enabled: true
data:
  springdoc-name: member-service
server:
  port: 8090